# Generated by Django 4.2 on 2023-05-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
