# Generated by Django 4.2 on 2023-05-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_balance_comment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
