# Generated by Django 4.2 on 2023-05-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('balance', models.PositiveBigIntegerField()),
            ],
        ),
    ]
