# Generated by Django 4.2 on 2023-05-13 20:54

import django.core.validators
from django.db import migrations, models

import cooking_core.general.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'owner',
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[cooking_core.general.validators.HexStringValidator(64)]
                    )
                ),
                (
                    'transaction_fee',
                    models.PositiveBigIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    )
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
